name: github pages

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '16.x'

    - name: Build datasets
      env:
        DATAHUB_REPO_NAME: ${{ secrets.DATAHUB_REPO_NAME }}
      run: |
        curl https://raw.githubusercontent.com/datopian/next.datahub.io/main/scripts/deploy-github-pages.sh > datahub.sh 
        git config --local user.email "$(git log --format='%ae' HEAD^!)"
        git config --local user.name "$(git log --format='%an' HEAD^!)"
        source ./datahub.sh
